import { FieldServiceContent, InstallationContent } from '@/types/report'

export const defaultFieldServiceContent = (): FieldServiceContent => ({
  fse_name: '',
  report_date: '',
  customer: '',
  location: '',
  crm_case_id: '',
  model: '',
  site_survey: '',
  noise_level: '',
  main_user: '',
  sid: '',
  tel: '',
  eq_id: '',
  email: '',
  service_type: '',
  tool_status: '',
  start_date: '',
  start_time: '',
  end_date: '',
  end_time: '',
  end_time_note: '고객사 출문 시간',
  problem_statement: '',
  target_statement: '',
  daily_note: '',
  progress_pct: 0,
  critical_items: [{ text: '', sub_items: [''] }],
  data_location: '',
  work_completion: {
    type: '',
    reason: '',
    detail: '',
    time_log: '',
  },
  images: [],
})

export const defaultInstallationContent = (): InstallationContent => ({
  fse_name: '',
  report_date: '',
  customer: '',
  location: '',
  crm_case_id: '',
  model: '',
  site_survey: '',
  noise_level: '',
  main_user: '',
  sid: '',
  tel: '',
  eq_id: '',
  email: '',
  est_complete_date: '',
  total_cycle_time: '',
  action_chart: [{ item: '', committed: '', actual_pct: 0 }],
  critical_items: [{ title: '', detail: '', next_plan: '' }],
  images: [],
})
